### PR TITLE
hotfix for python 2.7 support in scipy

### PR DESCRIPTION
**Pull request by hoffmansc**
scipy 1.3.0 no longer supports Python 2.7

eventually we should do the same but for now we can do this

### CODE REVIEW

**Comment by adrinjalali** [comment]
Any reason AIF360 still supports python2? It's a new library, it has no reason to support python2. This week probably the new sklearn will be released and it also doesn't support python2.

**Comment by hoffmansc** [comment]
I agree. I can't think of a good reason to continue supporting it...

**Comment by nrkarthikeyan** [comment]
Agree with @hoffmansc and @adrinjalali

**Comment by hoffmansc** [comment]
Then maybe we should just do that now instead of this. Is there anything other than the README, Travis tests, and maybe setup.py that needs to be changed?

**Comment by nrkarthikeyan** [comment]
@krvarshney, @michaelhind, @animeshsingh --- what do you all think about removing support for python 2? The one in pypi will still have support until the new version gets in there.

**Comment by animeshsingh** [comment]
+1 on that. Python 2 should mostly be going out now...

**Comment by michaelhind** [comment]
+1

**Comment by krvarshney** [comment]
makes sense

**Comment by krvarshney** [comment]
makes sense

**Comment by hoffmansc** [comment]
Cool. Closing this then.

**Pull request closed without merging**
